### PR TITLE
api: add query size to query config

### PR DESCRIPTION
**Pull request by MJedr**
ref: inspirehep/inspirehep#2334

### CODE REVIEW

**Review by drjova — APPROVED** [review]

**Comment by michamos** [comment]
how does this solve anything? you don't know in advance how many records reference a given record. What if there are more than 10000?

**Comment by MJedr** [comment]
I was thinking to add `size=10000` in reference matcher config, I thought it is enough results

**Comment by michamos** [comment]
It should be enough in most cases, but not necessarily always. Maybe we should change the code in hep to do a scroll directly instead of using the matcher? it doesn't seem like the matcher is super useful in this case anyhow.

**Comment by drjova** [comment]
I would merge this anyway

**Pull request merged**
