### PR TITLE
api: match -> path, search -> search_path

### PR DESCRIPTION
**Pull request by jacquerie**
Closes https://github.com/inspirehep/inspire-matcher/issues/21.

### CODE REVIEW

**Comment by jacquerie** [comment]
@david-caro, do you know of any downsides for this style of deprecations?

**Comment by david-caro** [comment]
I think that we are using them in the forms to search for existing records (in the arxiv/doi validators). Probably also in the workflows already_existing step.

**Comment by david-caro** [comment]
But specifically about the deprecation warnings, nop, just that we might ignore them :/

**Comment by jacquerie** [comment]
> just that we might ignore them :/

That's ok by me, what I wanted to avoid is to spam a logging system!

**Comment by david-caro** [comment]
Should be no problem, at least for now. In last instance, we can disable warnings in production.

**Pull request merged**
