### PR TITLE
api: allow using callables as validators

### PR DESCRIPTION
**Pull request by david-caro**
Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by jacquerie** [comment]
Can you add the `Sem-ver: adds new feature` trailer like in https://github.com/inspirehep/inspire-matcher/pull/32/commits/cb3119e1d1b1717ce6f12903edd1c7f3414ed30f ? I'm trying to stick to semantic versioning as much as possible in this repository.

**Comment by david-caro** [comment]
It can be added to the merge commit (from the github ui if merged from there). Or you prefer it from the PR commit?

**Comment by jacquerie** [comment]
> It can be added to the merge commit (from the github ui if merged from there).

Ah, right, I forgot about this option!

**Comment by david-caro** [comment]
I find it nicer when you decide when merging the review what type of change it is :)

**Comment by jacquerie** [comment]
Since this needed to be rebased anyway I took the liberty of modifying the commit message. In particular, there's no need to specify `api.match`, as, [by design](https://github.com/inveniosoftware-contrib/invenio-matcher/issues/2), the API only contains that method.

**Pull request merged**
